#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa ebin

main(_) ->
    application:start(metrics),
    metrics:add_writer(metrics_csv),
    metrics_gauge:append(potatoe, 42),
    metrics_gauge:append(potatoe, 41),
    metrics_gauge:append(potatoe, 43),
    metrics_csv:start_link(),
    metrics:dump(metrics_csv).
    